LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY contador IS
    PORT(CLK, RST: IN STD_LOGIC;
         CUENTA: BUFFER STD_LOGIC_VECTOR(3 DOWNTO 0)); 
END ENTITY;

ARCHITECTURE BEAS OF contador IS
BEGIN 
    PROCESS(CLK, RST)
    BEGIN
        IF RST = '1' THEN
            CUENTA <= "0000";
        ELSIF RISING_EDGE(CLK) THEN
            IF CUENTA = "1001" THEN  -- Límite en 9 (1001 binario)
                CUENTA <= "0000";
            ELSE
                CUENTA <= CUENTA + 1;
            END IF;
        END IF;
    END PROCESS;
END BEAS;