LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;
ENTITY vga IS
PORT(RST: IN STD_LOGIC;
	  CLK: IN STD_LOGIC; 
	  VIDEO: OUT STD_LOGIC; 
	  HPOS: BUFFER INTEGER RANGE 0 TO 799; 
	  VPOS: BUFFER INTEGER RANGE 0 TO 524; 
	  HSYNC, VSYNC: out STD_LOGIC); 
END vga;
ARCHITECTURE BEAS OF vga IS
CONSTANT HD: INTEGER := 639; 
CONSTANT VD: INTEGER := 479; 
CONSTANT HFP: INTEGER := 16; 
CONSTANT HSP: INTEGER := 96; 
CONSTANT HBP: INTEGER := 48; 
CONSTANT VFP: INTEGER := 10; 
CONSTANT VSP: INTEGER := 2; 
CONSTANT VBP: INTEGER := 33; 
BEGIN
	PROCESS(CLK, RST) 
	BEGIN
		IF RST = '1' THEN
			HPOS <= 0;
			ELSIF RISING_EDGE (CLK) THEN
				IF HPOS = (HD + HFP + HSP + HBP) THEN
					HPOS <= 0;
				ELSE
					HPOS <= HPOS + 1;
				END IF;
			END IF;
	END PROCESS;
	PROCESS(CLK, RST, HPOS) 
	BEGIN
		IF RST = '1' THEN
			VPOS <= 0;
			ELSIF RISING_EDGE (CLK) THEN
				IF HPOS = (HD + HFP + HSP + HBP) THEN
					IF VPOS = (VD + VFP + VSP + VBP) THEN
						VPOS <= 0;
					ELSE
						VPOS <= VPOS + 1;
					END IF;
				END IF;
			END IF;
	END PROCESS;
	PROCESS(CLK, RST, HPOS) 
	BEGIN
		IF RST = '1' THEN
			HSYNC <= '0';
		ELSIF FALLING_EDGE(CLK) THEN
			IF HPOS <= (HD + HFP) OR HPOS > (HD + HFP + HSP) THEN
				HSYNC <= '1';
			ELSE
				HSYNC <= '0';
			END IF;
		END IF;
	END PROCESS;
	PROCESS(CLK, RST, VPOS) 
	BEGIN
		IF RST = '1' THEN
			VSYNC <= '0';
		ELSIF FALLING_EDGE(CLK) THEN
			IF VPOS <= (VD + VFP) OR VPOS > (VD + VFP + VSP) THEN
				VSYNC <= '1';
			ELSE
				VSYNC <= '0';
			END IF;
		END IF;
	END PROCESS;
	PROCESS(CLK, RST, HPOS, VPOS) 
	BEGIN
		IF RST = '1' THEN
			VIDEO <= '0';
		ELSIF FALLING_EDGE(CLK) THEN
			IF HPOS <= HD AND VPOS <= VD THEN
				VIDEO <= '1';
			ELSE
				VIDEO <= '0';
			END IF;
		END IF;
	END PROCESS;
END BEAS;
