LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;
USE IEEE.STD_LOGIC_UNSIGNED.ALL;

ENTITY COMP IS
    PORT(CLK: IN STD_LOGIC;
         CONT: IN STD_LOGIC_VECTOR(2 DOWNTO 0);  -- 3 bits (0-7)
         CT: IN STD_LOGIC_VECTOR(2 DOWNTO 0);    -- Threshold 3 bits
         PWM: OUT STD_LOGIC);
END ENTITY;

ARCHITECTURE BEAS OF COMP IS
    SIGNAL CONT_SAMPLED: STD_LOGIC_VECTOR(2 DOWNTO 0);
    SIGNAL CT_SAMPLED: STD_LOGIC_VECTOR(2 DOWNTO 0);
BEGIN 
    PROCESS(CLK)
    BEGIN
        IF RISING_EDGE(CLK) THEN
            CONT_SAMPLED <= CONT;
            CT_SAMPLED <= CT;
            
            IF CONT_SAMPLED < CT_SAMPLED THEN
                PWM <= '1';
            ELSE
                PWM <= '0';
            END IF;
        END IF;
    END PROCESS;
END BEAS;