LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY divisor IS
	GENERIC(FREC: INTEGER := 5000000); -- FREC = (50MHz)/2*(FRECUENCIA_DESEADA) -1
	PORT(CLK_MST: IN STD_LOGIC;
		  CLK: BUFFER STD_LOGIC);
END ENTITY;

ARCHITECTURE BEAS OF divisor IS
SIGNAL AUX: INTEGER RANGE 0 TO FREC; 

BEGIN 
	PROCESS(CLK_MST)
	BEGIN
		IF RISING_EDGE(CLK_MST) THEN
			IF AUX = 0 THEN
				CLK <= NOT CLK;
				AUX <= FREC;
			ELSE
				AUX <= AUX -1;
			END IF;
		END IF;
	END PROCESS;
END BEAS;